using System.Collections.Generic;
using Snm.WaterSystem.Buoyancy;
using Snm.WaterSystem.Wave;
using UnityEngine;

namespace Snm.WaterSystem
{
    public class WaterSystemMB : MonoBehaviour
    {
        [SerializeField] private WaterConfigSO configAsset;
        [SerializeField] private Camera sourceCamera;

        [Header("Mesh Bake")]
        [Tooltip("Baked water surface mesh (UV1 carries shore distance / along-shore arc). Generated by the Bake Water Mesh button in this component.")]
        [SerializeField] private Mesh bakedMesh;
        [SerializeField] private List<GameObject> terrainObjects = new();
        [SerializeField] private Vector2 waterSize = new(30f, 30f);
        [SerializeField] private float gridCellSize = 1f;
        [SerializeField] private float maxShoreDistance = 4f;
        [SerializeField] private float alongShoreTiling = 0.1f;

        public Mesh BakedMesh => bakedMesh;
        public List<GameObject> TerrainObjects => terrainObjects;
        public Vector2 WaterSize => waterSize;
        public float GridCellSize => gridCellSize;
        public float MaxShoreDistance => maxShoreDistance;
        public float AlongShoreTiling => alongShoreTiling;

        private WaterSystemHandle _handle;
        private IEnumerable<IWaveDisturber> _disturbers;
        private IEnumerable<IBuoyant> _buoyants;

        /// <summary>
        /// The active water system handle. Available after <see cref="Start"/> has run.
        /// </summary>
        public WaterSystemHandle Handle => _handle;

        /// <summary>
        /// Provides a live disturber source before Start() runs.
        /// Call this immediately after the prefab is instantiated (e.g. from WaterEntity.OnInitialized).
        /// The list is held by reference and re-enumerated each frame, so registration changes
        /// made to the source list are picked up automatically.
        /// </summary>
        public void SetDisturbers(IEnumerable<IWaveDisturber> disturbers)
        {
            _disturbers = disturbers;
        }

        /// <summary>
        /// Provides a live buoyant source before Start() runs.
        /// Same pattern as <see cref="SetDisturbers"/>.
        /// </summary>
        public void SetBuoyants(IEnumerable<IBuoyant> buoyants)
        {
            _buoyants = buoyants;
        }

        private void Awake()
        {
            if (!isActiveAndEnabled) return;
            if (!sourceCamera) sourceCamera = Camera.main;
        }

        private void Start() => Setup();
        private void OnDestroy() => Teardown();

        [ContextMenu("Setup")]
        private void Setup()
        {
            if (!isActiveAndEnabled) return;
            if (!ValidateConfig()) return;

            _handle = WaterSystemFactory.Create(configAsset.Config, sourceCamera, _disturbers, _buoyants, transform, bakedMesh);
        }

        [ContextMenu("Teardown")]
        private void Teardown()
        {
            _handle?.Dispose();
            _handle = null;
        }

        private bool ValidateConfig()
        {
            if (sourceCamera == null)
            {
                Debug.LogError("[WaterSystem] Source camera is not assigned.", this);
                return false;
            }
            if (configAsset == null)
            {
                Debug.LogError("[WaterSystem] WaterConfigSO is not assigned.", this);
                return false;
            }
            var config = configAsset.Config;
            return config.surface.waterSurfaceShader != null || config.surface.waterSurfaceMaterial != null;
        }

#if UNITY_EDITOR
        private void OnDrawGizmos()
        {
            Gizmos.matrix = transform.localToWorldMatrix;
            Gizmos.color = Color.cyan;
            Gizmos.DrawWireCube(Vector3.zero, new Vector3(waterSize.x, 0, waterSize.y));
        }

        [ContextMenu("Auto-assign config references")]
        private void AutoAssignConfigReferences()
        {
            if (configAsset) WaterSystemTestWindow.AutoAssignConfigReferences(configAsset.Config);
        }

#endif
    }
}
